class_name PhysicsLayerMasks
extends Object

const RAY_LAYER_LEDGE := 16
const RAY_MOVEMENT_GROUND := 9 | RAY_LAYER_LEDGE
const RAY_MOVEMENT_ELEVATED := 1152 | RAY_LAYER_LEDGE
const CHARACTER_PLAYER := 2
const CHARACTER_INTERACTABLE := 8
const AREA_QUERY_TILE_MOVERS := CHARACTER_PLAYER | CHARACTER_INTERACTABLE
