class_name PhysicsLayerMasks
extends Object

const RAY_MOVEMENT_GROUND := 9
const RAY_MOVEMENT_ELEVATED := 1152
const CHARACTER_PLAYER := 2
const CHARACTER_INTERACTABLE := 8
const AREA_QUERY_TILE_MOVERS := CHARACTER_PLAYER | CHARACTER_INTERACTABLE
